---
title: "Merging_POCA_datasets"
output: html_document
date: "2023-07-10"
---
Load packages
```{r}
library(pbapply)
library(stringr)
library(ggplot2)
library(reshape2)
library(stringr)
library(ggrepel)
library(RColorBrewer)
library(readxl)
library(tidyverse)
setwd("C:/Users/andbp/Documents/R_data/AP2-150_HepG2-wt-SRBI_expression/")
```

Read results files (as .csv)
```{r}
df.labels <- read.csv("uniprot_accession_gene.csv")
df1 <- read.csv("AP2-136_133_FP22_parental-vs-SRBI-HepG2_HDL-chol-JF570_11dec24.csv")
df2 <- read.csv("AP2-150-FP22-no-norm_fc1-p05-expression_20june25.csv")
```

Create lookup table from df.labels
```{r}
# Create lookup table from first data frame
lookup <- df.labels[, c("ProteinID", "label")]
```

Merge based on "ProteinID" aka Uniprot Accession
```{r}
# Your existing code up to the merge
df_list <- list(HDL.chol.JF570.wt.vs.SRBI = df1, wt.vs.SRBI_expression = df2)

df_list <- lapply(df_list, function(df) {
  df$label <- NULL # remove existing label
  df <- merge(df, lookup, by = "ProteinID", all.x = TRUE)
  return(df)
})
merged_df <- Reduce(function(x, y) merge(x, y, by = c("ProteinID", "label"), all = TRUE), df_list)
names(merged_df) <- c(
  "ProteinID",
  "label", 
  "foldchange.HDL.chol.JF570.wt.vs.SRBI",
  "p_value.HDL.chol.JF570.wt.vs.SRBI", 
  "diffexpressed.HDL.chol.JF570.wt.vs.SRBI",
  "selected_labels.HDL.chol.JF570.wt.vs.SRBI",
  "foldchange.wt.vs.SRBI_expression",
  "p_value.wt.vs.SRBI_expression",
  "diffexpressed.wt.vs.SRBI_expression", 
  "selected_labels.wt.vs.SRBI_expression"
)
```

```{r}
write.csv(merged_df, file = "AP2-133vs136_150-no-norm_merge_20june25.csv", row.names = FALSE)
```

